### ISSUE TITLE
Multi monitor support

### ISSUE THREAD

**Issue by ViggoGaming** [Wilnath/asetroot#1]
Hey.
Is there any way to get multi monitor support for this program?
Right now my second monitor is just black when i run asetroot...

**Comment by Wilnath** [comment]
Hey!

asetroot doesn't have multi monitor support, and I don't know how to go about adding it either, sorry!

I'd consider using [paperview](https://github.com/glouw/paperview) as an alternative, since it seems to support multiple monitors.
