### ISSUE TITLE
Failed to load images although they are in %05d.gif format

### ISSUE THREAD

**Issue by 6MrRobot9** [Wilnath/asetroot#2]
`~ >>> convert w1.gif -coalesce -resize 1920x1080 scene/%05d.gif`
`~/asetroot >>> ./asetroot scene/ -t 50`
`Failed loading images from the folder scene/`
`Format: %05d.gif`

**Comment by Wilnath** [comment]
Hey!
If I'm understanding this correctly, you created a folder with the images called `~/scene/`. When starting asetroot you are in the asetroot directory, which means that the argument `scene/` points to a folder `~/asetroot/scene/`, which doesn't exist and throws the error. To fix this, you could type  
`./asetroot ../scene/ -t 50` if you're in the asetroot directory   
or  
`./asetroot/asetroot scene/ -t 50` if you're in the home directory  
  
Apologies for the generic error though! Error handling in this program is *very* basic
